### ISSUE TITLE
Falling Zepplines

### ISSUE THREAD

**Issue by LySoon** [schwim0341/esx_anticheat#1]
im currently using esx_anticheat + npc_control
but.. idk why but some blimps + chopters are falling from sky to the players head .__.

how can i fix that ?

**Comment by schwim0341** [comment]
Raise the ped threshold in the config file if you feel it's too low to allow for the normal number of peds on the map.

**Comment by LySoon** [comment]
İ want no limit ?
Like can i set it to infine by setting it to -1
?? Or can i make it 9999??

**Comment by LySoon** [comment]
Fixed ^^
i set it to 99999
