### ISSUE TITLE
ObjectsBL

### ISSUE THREAD

**Issue by Hentari** [schwim0341/esx_anticheat#3]
If i remove something from Config.ObjectsBL for example "a_c_cow" the cow still disappear.

**Comment by Chainedster** [comment]
Had this issue and it's caused from line 214 in anticheat-cl.lua

```
Citizen.CreateThread(function()
    while (true) do
        Citizen.Wait(500)
        KillAllPeds()
        DeleteEntity(ped)
    end
end)
```

just comment all that out and animals such as deer etc will spawn in again like normal

**Comment by schwim0341** [comment]
It's actually this line in function KillAllPeds:
```LUA
 if pedweapon == -1312131151 or not IsPedHuman(ped) then 
```

Your "fix" breaks the check completely while removing **or not IsPedHuman(ped)** stops the animals from disappearing while keeping the protection in place.
